
User.destroy_all
Cause.destroy_all
Event.destroy_all

@blm_user = User.create!(username: 'BLM Admin', email: 'blmadmin@email.com', password: '123456')
@hrc_user = User.create!(username: 'HRC Admin', email: 'hrcadmin@email.com', password: '123456')
@pp_user = User.create!(username: 'PP Admin', email: 'ppadmin@email.com', password: '123456')
@et_user = User.create!(username: 'ET Admin', email: 'etadmin@email.com', password: '123456')
@sc_user = User.create!(username: 'SC Admin', email: 'scadmin@email.com', password: '123456')
@crp_user = User.create!(username: 'CRP Admin', email: 'crpadmin@email.com', password: '123456')


@blm = Cause.create!(name: 'Black Lives Matter', image: 'https://i.imgur.com/IYXQOW2.png', user: @blm_user)
@hrc = Cause.create!(name: 'Human Rights Campagin', image: 'https://i.imgur.com/G7vTT2D.png', user: @hrc_user)
@pp = Cause.create!(name: 'Planned Parenthood', image: 'https://i.imgur.com/jasYUU0.png', user: @pp_user)
@et = Cause.create!(name: 'Everytown for Gun Safety', image: 'https://i.imgur.com/0ixrxkR.png', user: @et_user)
@sc = Cause.create!(name: 'Street Children', image: 'https://i.imgur.com/Lj5v0bd.png', user: @sc_user)
@crp = Cause.create!(name: 'Climate Reality Project', image: 'https://i.imgur.com/xzuC10N.png', user: @crp_user)


@unity_march = Event.create!(name: 'Unity March', reason: 'Support in San Jose', location: 'SAP Center, San Jose', age_group: '18+', cause: @blm, user: @blm_user, image: 'https://i.imgur.com/9h8WXxT.png', date: '10/30/20')
@social_justice = Event.create!(name: 'Social Justice Forum', reason: "Cause, George, she wants to go to the dance with you, she just doesn't know it yet. That's why we got to show her that you, George McFly, are a fighter. You're somebody who's gonna stand up for yourself, someone who's gonna protect her.", location: 'SAP Center, San Jose', age_group: '18+', cause: @blm, user: @blm_user, image: 'https://i.imgur.com/9h8WXxT.png', date: '11/01/20')
@march_for_justice = Event.create!(name: 'March for Justice', reason: "Doc, you gotta help me. you were the only one who knows how your time machine works.", location: 'SAP Center, San Jose', age_group: 'all ages', cause: @blm, user: @blm_user, image: 'https://i.imgur.com/9h8WXxT.png', date: '12/15/20')
@town_hall = Event.create!(name: 'Town Hall', reason: "You got a real attitude problem, McFly. You're a slacker. You remind me of you father when he went her, he was a slacker too.", location: 'SAP Center, San Jose', age_group: '18+', cause: @blm, user: @blm_user, image: 'https://i.imgur.com/9h8WXxT.png', date: '12/15/20')
@community_outreach = Event.create!(name: 'Community Outreach', reason: 'Hey Dad, George, hey, you on the bike.', location: 'SAP Center, San Jose', age_group: 'all ages', cause: @blm, user: @blm_user, image: 'https://i.imgur.com/9h8WXxT.png', date: '01/07/21')

@phone_bank = Event.create!(name: 'Everytown Phone Bank', reason: 'Inform voters of laws in their state.', location: 'Everytown Office, San Francisco', age_group: '18+', cause: @et, user: @et_user, image: 'https://i.imgur.com/V0NFhJ7.png', date: '10/31/20')
@town_meeting = Event.create!(name: 'Town Meeting', reason: 'Hypori aayla darth desann beru tatooine endor ysanne. Biggs derlin mirta ssi-ruuk shmi biggs hutt.', location: 'Everytown Office, San Francisco', age_group: 'all ages', cause: @et, user: @et_user, image: 'https://i.imgur.com/V0NFhJ7.png', date: '10/31/20')
@school_walkout = Event.create!(name: 'School Walk-out', reason: 'Arkanian tapani lando darth garm walon. Xexto felth corellia altyr malastare quinlan halla. Xappyh fisto mohc grievous paaerduag moff palpatine charal.', location: 'Everytown Office, San Francisco', age_group: '18+', cause: @et, user: @et_user, image: 'https://i.imgur.com/V0NFhJ7.png', date: '11/22/20')
@capital_hill = Event.create!(name: 'Capital Hill Stand', reason: ' Darth jabba kast rodian max kohl boltrunians tython. Cathar massassi sabé klatooinian wicket skywalker binks.', location: 'Everytown Office, San Francisco', age_group: 'all ages', cause: @et, user: @et_user, image: 'https://i.imgur.com/V0NFhJ7.png', date: '12/01/20')
@teacher_support = Event.create!(name: 'Support Teachers in Schools', reason: "We don’t serve their kind here! What? Your droids. They’ll have to wait outside. We don’t want them here. Listen, why don’t you wait out by the speeder. We don’t want any trouble.", location: 'Everytown Office, San Francisco', age_group: '18+', cause: @et, user: @et_user, image: 'https://i.imgur.com/V0NFhJ7.png', date: '12/05/20')

@escort = Event.create!(name: 'Planned Parenthood Volunteer Escort', reason: 'Protect people entering and leaving Planned Parenthood.', location: 'Planned Parenthood, Santa Clara', age_group: '18+', cause: @pp, user: @pp_user, image: 'https://i.imgur.com/dxaMeYI.png', date: '11/15/20')
@escort1 = Event.create!(name: 'Planned Parenthood Volunteer Escort', reason: 'Harry shook himself mentally; he was being stupid. There was no one in the house with him except Uncle Vernon, Aunt Petunia, and Dudley, and they were plainly still asleep, their dreams untroubled and painless.', location: 'Planned Parenthood, Santa Clara', age_group: '18+', cause: @pp, user: @pp_user, image: 'https://i.imgur.com/dxaMeYI.png', date: '11/15/20')
@escort2 = Event.create!(name: 'Planned Parenthood Volunteer Escort', reason: 'Moodys magical eye left the map and fixed, quivering, upon Harry. It was a penetrating glare, and Harry had the impression that Moody was sizing him up, wondering whether to answer or not, or how much to tell him.', location: 'Planned Parenthood, Santa Clara', age_group: '18+', cause: @pp, user: @pp_user, image: 'https://i.imgur.com/dxaMeYI.png', date: '11/15/20')
@escort3 = Event.create!(name: 'Planned Parenthood Volunteer Escort', reason: 'The Quidditch field was no longer smooth and flat. It looked as though somebody had been building long, low walls all over it that twisted and crisscrossed in every direction.', location: 'Planned Parenthood, Santa Clara', age_group: '18+', cause: @pp, user: @pp_user, image: 'https://i.imgur.com/dxaMeYI.png', date: '11/15/20')
@escort4 = Event.create!(name: 'Planned Parenthood Volunteer Escort', reason: 'Half-giant jinxes peg-leg gillywater broken glasses large black dog Great Hall. Nearly-Headless Nick now string them together, and answer me this, which creature would you be unwilling to kiss?', location: 'Planned Parenthood, Santa Clara', age_group: '18+', cause: @pp, user: @pp_user, image: 'https://i.imgur.com/dxaMeYI.png', date: '11/15/20')

@pride = Event.create!(name: 'San Jose Pride', reason: 'Show your support for love! Come join HRC for a day of dancing, fun and love.', location: 'Downtown San Francisco', age_group: 'all ages', cause: @hrc, user: @hrc_user, image: 'https://i.imgur.com/9WIzARV.png', date: '11/05/20')
@pride1 = Event.create!(name: 'Debunking the Myths: Transgender Health & Well-Being', reason: "Bees do have a smell, you know, and if they don't they should, for their feet are dusted with spices from a million flowers.", location: 'Downtown San Francisco', age_group: 'all ages', cause: @hrc, user: @hrc_user, image: 'https://i.imgur.com/9WIzARV.png', date: '11/05/20')
@pride2 = Event.create!(name: 'San Francisco Pride', reason: "Some people turn sad awfully young. No special reason, it seems, but they seem almost to be born that way. They bruise easier, tire faster, cry quicker, remember longer and, as I say, get sadder younger than anyone else in the world. I know, for I'm one of them." , location: 'Downtown San Francisco', age_group: 'all ages', cause: @hrc, user: @hrc_user, image: 'https://i.imgur.com/9WIzARV.png', date: '11/05/20')
@pride3 = Event.create!(name: 'Debunking Common Myths about HIV', reason: "I want to feel all there is to feel, he thought. Let me feel tired, now, let me feel tired. I mustn't forget, I'm alive, I know I'm alive, I mustn't forget it tonight or tomorrow or the day after that.", location: 'Downtown San Francisco', age_group: 'all ages', cause: @hrc, user: @hrc_user, image: 'https://i.imgur.com/9WIzARV.png', date: '11/05/20')
@pride4 = Event.create!(name: 'San Jose Pride', reason: "Where would you like to go, what would you really like to do with your life?", location: 'Downtown San Francisco', age_group: 'all ages', cause: @hrc, user: @hrc_user, image: 'https://i.imgur.com/9WIzARV.png', date: '11/05/20')

@food_drive = Event.create!(name: 'Street Children Food Drive', reason: 'Help fill backpacks with necessities to pass out to the local community in need.', location: 'Street Children Warehouse, San Jose', age_group: 'all ages', cause: @sc, user: @sc_user, image: 'https://i.imgur.com/5bJpJAV.png', date: '12/05/20')
@fundraiser = Event.create!(name: 'Fundraiser for Food', reason: 'Whispers blue birdses stretched Brandybucks spot west! Northeast Gamgee walked helpful enjoying! Orchards Dale star! World malt Brandywine decided bargeman. Pleased crunchable Proudfeet hour embrace thicket swish dies!', location: 'Street Children Warehouse, San Jose', age_group: 'all ages', cause: @sc, user: @sc_user, image: 'https://i.imgur.com/5bJpJAV.png', date: '12/15/20')
@fundraiser1 = Event.create!(name: 'Fundraiser for Shelter', reason: "Toss mattered blossom threat then crack tools Goblin-men knocking princess meets. Visitors forgot Kili's dump ringing 1400? Until Éomer grocer strength carcasses batses beg particularly rally interrupt." , location: 'Street Children Warehouse, San Jose', age_group: 'all ages', cause: @sc, user: @sc_user, image: 'https://i.imgur.com/5bJpJAV.png', date: '12/27/20')
@fundraiser2 = Event.create!(name: 'Street Children Food Drive', reason: 'Help fill backpacks with necessities to pass out to the local community in need.', location: 'Street Children Warehouse, San Jose', age_group: 'all ages', cause: @sc, user: @sc_user, image: 'https://i.imgur.com/5bJpJAV.png', date: '12/30/20')
@food_drive1 = Event.create!(name: 'Street Children Food Drive', reason: ' Mortal Durin cliff 42 move. That is no trinket you carry. Arwen Evenstar listen board. Rejoice weather Oakenshield laugh!', location: 'Street Children Warehouse, San Jose', age_group: 'all ages', cause: @sc, user: @sc_user, image: 'https://i.imgur.com/5bJpJAV.png', date: '12/30/20')

@climate_talk = Event.create!(name: 'Climate Change Talk', reason: 'Inform voters of what they can do locally to push for real changes in government regarding climate.', location: '5th Avenue Park, Downtown San Jose', age_group: '18+', cause: @crp, user: @crp_user, image: 'https://i.imgur.com/y7XAsuR.png', date: '12/10/20')
@climate_talk = Event.create!(name: 'Climate Change Talk', reason: 'Science is no more than an investigation of a miracle we can never explain, and art is an interpretation of that miracle.', location: '5th Avenue Park, Downtown San Jose', age_group: '18+', cause: @crp, user: @crp_user, image: 'https://i.imgur.com/y7XAsuR.png', date: '12/10/20')
@climate_talk = Event.create!(name: 'Climate Change Talk', reason: "I'm not anyone, I'm just myself; whatever I am, I am something, and now I'm something you can't help.", location: '5th Avenue Park, Downtown San Jose', age_group: '18+', cause: @crp, user: @crp_user, image: 'https://i.imgur.com/y7XAsuR.png', date: '12/10/20')
@climate_talk = Event.create!(name: 'Climate Change Talk', reason: "It is good to renew one's wonder, said the philosopher. Space travel has again made children of us all.", location: '5th Avenue Park, Downtown San Jose', age_group: '18+', cause: @crp, user: @crp_user, image: 'https://i.imgur.com/y7XAsuR.png', date: '12/10/20')
@climate_talk = Event.create!(name: 'Climate Change Talk', reason: "Can't you recognize the human in the inhuman?", location: '5th Avenue Park, Downtown San Jose', age_group: '18+', cause: @crp, user: @crp_user, image: 'https://i.imgur.com/y7XAsuR.png', date: '12/10/20')  
